### ISSUE TITLE
Customize placement

### ISSUE THREAD

**Issue by thebuilder** [voorhoede/datocms-plugin-custom-page#1]
Hey! 

Thanks for the plugin - Seems to work great. 💪
But, it would be really nice if we had the option to specify (or omit) the [placement](https://github.com/datocms/plugins-sdk/blob/master/packages/sdk/src/types.ts#L168) value. Some usecases it makes more sense if it's the last item in the menu - E.g. I might use it to embed analytics.

Maybe a better default would be to not have it specified as default?🤔

**Comment by Siilwyn** [comment]
👋 thank you for shooting in this issue!
Feel free to create a PR if you have the time, otherwise it'll probably be picked up next week.

**Comment by thebuilder** [comment]
No rush🙏

**Comment by velomovies** [comment]
As of version `1.1.0` you should be able to change the placement of the menu item as well as adding a group title when used in the settings sidebar
